//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PureVPN.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MixpanelEvents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MixpanelEvents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PureVPN.Service.MixpanelEvents", typeof(MixpanelEvents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_accept_connection_over_connection_popup.
        /// </summary>
        public static string app_accept_connection_over_connection_popup {
            get {
                return ResourceManager.GetString("app_accept_connection_over_connection_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_accept_switch_server.
        /// </summary>
        public static string app_accept_switch_server {
            get {
                return ResourceManager.GetString("app_accept_switch_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_accept_switch_to_p2p_enabled_location_popup.
        /// </summary>
        public static string app_accept_switch_to_p2p_enabled_location_popup {
            get {
                return ResourceManager.GetString("app_accept_switch_to_p2p_enabled_location_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_add_application_for_split.
        /// </summary>
        public static string app_add_application_for_split {
            get {
                return ResourceManager.GetString("app_add_application_for_split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_api_failure.
        /// </summary>
        public static string app_api_failure {
            get {
                return ResourceManager.GetString("app_api_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_api_response_time.
        /// </summary>
        public static string app_api_response_time {
            get {
                return ResourceManager.GetString("app_api_response_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_block_internet_iks.
        /// </summary>
        public static string app_block_internet_iks {
            get {
                return ResourceManager.GetString("app_block_internet_iks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_cancel_switch_server_popup.
        /// </summary>
        public static string app_cancel_switch_server_popup {
            get {
                return ResourceManager.GetString("app_cancel_switch_server_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_cancel_switch_to_p2p_enabled_location_popup.
        /// </summary>
        public static string app_cancel_switch_to_p2p_enabled_location_popup {
            get {
                return ResourceManager.GetString("app_cancel_switch_to_p2p_enabled_location_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_cancel_troubleshoot.
        /// </summary>
        public static string app_cancel_troubleshoot {
            get {
                return ResourceManager.GetString("app_cancel_troubleshoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_cancelled.
        /// </summary>
        public static string app_cancelled {
            get {
                return ResourceManager.GetString("app_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_change_language.
        /// </summary>
        public static string app_change_language {
            get {
                return ResourceManager.GetString("app_change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_cities_viewed.
        /// </summary>
        public static string app_cities_viewed {
            get {
                return ResourceManager.GetString("app_cities_viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_clear_notification.
        /// </summary>
        public static string app_clear_notification {
            get {
                return ResourceManager.GetString("app_clear_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_click_addon.
        /// </summary>
        public static string app_click_addon {
            get {
                return ResourceManager.GetString("app_click_addon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_click_addon_details.
        /// </summary>
        public static string app_click_addon_details {
            get {
                return ResourceManager.GetString("app_click_addon_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_click_cta_troubleshoot.
        /// </summary>
        public static string app_click_cta_troubleshoot {
            get {
                return ResourceManager.GetString("app_click_cta_troubleshoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_click_grace_period_popup.
        /// </summary>
        public static string app_click_grace_period_popup {
            get {
                return ResourceManager.GetString("app_click_grace_period_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_click_login.
        /// </summary>
        public static string app_click_login {
            get {
                return ResourceManager.GetString("app_click_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_click_notification.
        /// </summary>
        public static string app_click_notification {
            get {
                return ResourceManager.GetString("app_click_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_click_purchase.
        /// </summary>
        public static string app_click_purchase {
            get {
                return ResourceManager.GetString("app_click_purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_click_refer_a_friend.
        /// </summary>
        public static string app_click_refer_a_friend {
            get {
                return ResourceManager.GetString("app_click_refer_a_friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_click_retry_fetch_user_details.
        /// </summary>
        public static string app_click_retry_fetch_user_details {
            get {
                return ResourceManager.GetString("app_click_retry_fetch_user_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_click_setupdevice.
        /// </summary>
        public static string app_click_setupdevice {
            get {
                return ResourceManager.GetString("app_click_setupdevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_click_switch_server.
        /// </summary>
        public static string app_click_switch_server {
            get {
                return ResourceManager.GetString("app_click_switch_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_complete_troubleshoot.
        /// </summary>
        public static string app_complete_troubleshoot {
            get {
                return ResourceManager.GetString("app_complete_troubleshoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_connect.
        /// </summary>
        public static string app_connect {
            get {
                return ResourceManager.GetString("app_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_connected.
        /// </summary>
        public static string app_connected {
            get {
                return ResourceManager.GetString("app_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_credentials_not_found.
        /// </summary>
        public static string app_credentials_not_found {
            get {
                return ResourceManager.GetString("app_credentials_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_disconnected.
        /// </summary>
        public static string app_disconnected {
            get {
                return ResourceManager.GetString("app_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_done_kill_dedicatedip_session.
        /// </summary>
        public static string app_done_kill_dedicatedip_session {
            get {
                return ResourceManager.GetString("app_done_kill_dedicatedip_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_expiry_popup_shown.
        /// </summary>
        public static string app_expiry_popup_shown {
            get {
                return ResourceManager.GetString("app_expiry_popup_shown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_expiry_renew_clicked.
        /// </summary>
        public static string app_expiry_renew_clicked {
            get {
                return ResourceManager.GetString("app_expiry_renew_clicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_fail_fetch_account_info.
        /// </summary>
        public static string app_fail_fetch_account_info {
            get {
                return ResourceManager.GetString("app_fail_fetch_account_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_fail_fetch_user_details.
        /// </summary>
        public static string app_fail_fetch_user_details {
            get {
                return ResourceManager.GetString("app_fail_fetch_user_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_fail_get_connected_location.
        /// </summary>
        public static string app_fail_get_connected_location {
            get {
                return ResourceManager.GetString("app_fail_get_connected_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_fail_kill_dedicatedip_session.
        /// </summary>
        public static string app_fail_kill_dedicatedip_session {
            get {
                return ResourceManager.GetString("app_fail_kill_dedicatedip_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_fail_refer_a_friend_invite.
        /// </summary>
        public static string app_fail_refer_a_friend_invite {
            get {
                return ResourceManager.GetString("app_fail_refer_a_friend_invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_feedback_session.
        /// </summary>
        public static string app_feedback_session {
            get {
                return ResourceManager.GetString("app_feedback_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_fetch_account_info_failed.
        /// </summary>
        public static string app_fetch_account_info_failed {
            get {
                return ResourceManager.GetString("app_fetch_account_info_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_filter_list.
        /// </summary>
        public static string app_filter_list {
            get {
                return ResourceManager.GetString("app_filter_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_launched.
        /// </summary>
        public static string app_launched {
            get {
                return ResourceManager.GetString("app_launched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_location_load_time.
        /// </summary>
        public static string app_location_load_time {
            get {
                return ResourceManager.GetString("app_location_load_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_logged_in.
        /// </summary>
        public static string app_logged_in {
            get {
                return ResourceManager.GetString("app_logged_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_login_failed.
        /// </summary>
        public static string app_login_failed {
            get {
                return ResourceManager.GetString("app_login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_logout.
        /// </summary>
        public static string app_logout {
            get {
                return ResourceManager.GetString("app_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_mark_favorite.
        /// </summary>
        public static string app_mark_favorite {
            get {
                return ResourceManager.GetString("app_mark_favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_migration_popup_clicked.
        /// </summary>
        public static string app_migration_popup_clicked {
            get {
                return ResourceManager.GetString("app_migration_popup_clicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_migration_popup_shown.
        /// </summary>
        public static string app_migration_popup_shown {
            get {
                return ResourceManager.GetString("app_migration_popup_shown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_multiple_credentials_found.
        /// </summary>
        public static string app_multiple_credentials_found {
            get {
                return ResourceManager.GetString("app_multiple_credentials_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_ping_time.
        /// </summary>
        public static string app_ping_time {
            get {
                return ResourceManager.GetString("app_ping_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_proceed_kill_dedicatedip_session.
        /// </summary>
        public static string app_proceed_kill_dedicatedip_session {
            get {
                return ResourceManager.GetString("app_proceed_kill_dedicatedip_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_proceed_migration.
        /// </summary>
        public static string app_proceed_migration {
            get {
                return ResourceManager.GetString("app_proceed_migration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_rate_session.
        /// </summary>
        public static string app_rate_session {
            get {
                return ResourceManager.GetString("app_rate_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_receive_notification.
        /// </summary>
        public static string app_receive_notification {
            get {
                return ResourceManager.GetString("app_receive_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_request_store_rating.
        /// </summary>
        public static string app_request_store_rating {
            get {
                return ResourceManager.GetString("app_request_store_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_request_swap_token.
        /// </summary>
        public static string app_request_swap_token {
            get {
                return ResourceManager.GetString("app_request_swap_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_resume_internet_iks.
        /// </summary>
        public static string app_resume_internet_iks {
            get {
                return ResourceManager.GetString("app_resume_internet_iks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_return_web_login.
        /// </summary>
        public static string app_return_web_login {
            get {
                return ResourceManager.GetString("app_return_web_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_route_live_chat.
        /// </summary>
        public static string app_route_live_chat {
            get {
                return ResourceManager.GetString("app_route_live_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_route_web_login.
        /// </summary>
        public static string app_route_web_login {
            get {
                return ResourceManager.GetString("app_route_web_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_session_popup_rated.
        /// </summary>
        public static string app_session_popup_rated {
            get {
                return ResourceManager.GetString("app_session_popup_rated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_session_popup_shown.
        /// </summary>
        public static string app_session_popup_shown {
            get {
                return ResourceManager.GetString("app_session_popup_shown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_sort_list.
        /// </summary>
        public static string app_sort_list {
            get {
                return ResourceManager.GetString("app_sort_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_start_troubleshoot.
        /// </summary>
        public static string app_start_troubleshoot {
            get {
                return ResourceManager.GetString("app_start_troubleshoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_store_rating.
        /// </summary>
        public static string app_store_rating {
            get {
                return ResourceManager.GetString("app_store_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_submit_feedback.
        /// </summary>
        public static string app_submit_feedback {
            get {
                return ResourceManager.GetString("app_submit_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_toggle_iks.
        /// </summary>
        public static string app_toggle_iks {
            get {
                return ResourceManager.GetString("app_toggle_iks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_toggle_split.
        /// </summary>
        public static string app_toggle_split {
            get {
                return ResourceManager.GetString("app_toggle_split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_ttc.
        /// </summary>
        public static string app_ttc {
            get {
                return ResourceManager.GetString("app_ttc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_update_available.
        /// </summary>
        public static string app_update_available {
            get {
                return ResourceManager.GetString("app_update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_update_ignored.
        /// </summary>
        public static string app_update_ignored {
            get {
                return ResourceManager.GetString("app_update_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_updated.
        /// </summary>
        public static string app_updated {
            get {
                return ResourceManager.GetString("app_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_user_speed.
        /// </summary>
        public static string app_user_speed {
            get {
                return ResourceManager.GetString("app_user_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_user_speed_failed.
        /// </summary>
        public static string app_user_speed_failed {
            get {
                return ResourceManager.GetString("app_user_speed_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_utb.
        /// </summary>
        public static string app_utb {
            get {
                return ResourceManager.GetString("app_utb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_utc.
        /// </summary>
        public static string app_utc {
            get {
                return ResourceManager.GetString("app_utc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_already_connected_popup.
        /// </summary>
        public static string app_view_already_connected_popup {
            get {
                return ResourceManager.GetString("app_view_already_connected_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_connection_over_connection_popup.
        /// </summary>
        public static string app_view_connection_over_connection_popup {
            get {
                return ResourceManager.GetString("app_view_connection_over_connection_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_deeplink_popup.
        /// </summary>
        public static string app_view_deeplink_popup {
            get {
                return ResourceManager.GetString("app_view_deeplink_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_grace_period_popup.
        /// </summary>
        public static string app_view_grace_period_popup {
            get {
                return ResourceManager.GetString("app_view_grace_period_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_invalid_deeplink_popup.
        /// </summary>
        public static string app_view_invalid_deeplink_popup {
            get {
                return ResourceManager.GetString("app_view_invalid_deeplink_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_kill_dedicatedip_session_popup.
        /// </summary>
        public static string app_view_kill_dedicatedip_session_popup {
            get {
                return ResourceManager.GetString("app_view_kill_dedicatedip_session_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_live_chat_popup.
        /// </summary>
        public static string app_view_live_chat_popup {
            get {
                return ResourceManager.GetString("app_view_live_chat_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_migration_popup.
        /// </summary>
        public static string app_view_migration_popup {
            get {
                return ResourceManager.GetString("app_view_migration_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_notification.
        /// </summary>
        public static string app_view_notification {
            get {
                return ResourceManager.GetString("app_view_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_notification_center.
        /// </summary>
        public static string app_view_notification_center {
            get {
                return ResourceManager.GetString("app_view_notification_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_purchase_popup.
        /// </summary>
        public static string app_view_purchase_popup {
            get {
                return ResourceManager.GetString("app_view_purchase_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_refer_a_friend.
        /// </summary>
        public static string app_view_refer_a_friend {
            get {
                return ResourceManager.GetString("app_view_refer_a_friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_session_prompt.
        /// </summary>
        public static string app_view_session_prompt {
            get {
                return ResourceManager.GetString("app_view_session_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_setupdevice.
        /// </summary>
        public static string app_view_setupdevice {
            get {
                return ResourceManager.GetString("app_view_setupdevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_switch_server_popup.
        /// </summary>
        public static string app_view_switch_server_popup {
            get {
                return ResourceManager.GetString("app_view_switch_server_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_switch_to_p2p_enabled_location_popup.
        /// </summary>
        public static string app_view_switch_to_p2p_enabled_location_popup {
            get {
                return ResourceManager.GetString("app_view_switch_to_p2p_enabled_location_popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app_view_troubleshoot.
        /// </summary>
        public static string app_view_troubleshoot {
            get {
                return ResourceManager.GetString("app_view_troubleshoot", resourceCulture);
            }
        }
    }
}
